import NavBar from '../../components/NavBar'
import Footer from '../../components/Footer'
import '../../css/global.css'

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className="font-martian-mono content-center items-center h-screen w-screen">{children}</body>
        </html>
    )
}
