#!/usr/bin/env python3

"""
This tool fetches all the data stored in a google sheet database and converts it
into a json object.
Usage:
./tools/render-json-sheets
"""

#import library
import gspread
import json
import sys
import configparser

#Service client credential from oauth2client
from oauth2client.service_account import ServiceAccountCredentials

def fetch_all_fields():
    #Create scope
    scope = ['https://spreadsheets.google.com/feeds']

    #create some credential using that scope and content of startup_funding.json
    creds = ServiceAccountCredentials.from_json_keyfile_name('../database/mil_projects_auth.json',scope)

    #create gspread authorize using that credential
    client = gspread.authorize(creds)

    # Fetching url data
    config_obj = configparser.ConfigParser()
    config_file_path = '../database/mil_website_link'
    try:
        with open(config_file_path, 'r') as f:
            config_obj.read_file(f, config_file_path)
        sheet_details = config_obj['google sheets']
        link = sheet_details['url']
    except:
        print('Could not parse config file')

    #Now will can access our google sheets we call client.open on StartupName
    sheet = client.open_by_url(link)

    worksheet = sheet.get_worksheet(0)
    #Access all of the record inside that

    result = worksheet.get_all_records() # List[Dict[str, str]]
    for element in result:
        element['imageURL'] = 'https://drive.google.com/uc?id='+element['imageURL'][32:-17]
    convert_to_json = {element['Name']:element for element in result}

    original = sys.stdout
    sys.stdout = open('../database/projects_data.json', 'w')
    print(json.dumps(convert_to_json))
    sys.stdout = original


if __name__ == "__main__":
    fetch_all_fields()
