
name: Blog Image Upload & Cleanup

on:
  pull_request_target:
    types: [closed]
    paths:
      - "blogs/**"
      - "public/images/blogs/**"

jobs:
  upload-images:
    if: github.event.pull_request.merged == true && github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout blog repo
        uses: actions/checkout@v4
        with:
          path: blog-repo
          token: ${{ secrets.REPO_PAT }}

      - name: Checkout images repo
        uses: actions/checkout@v4
        with:
          repository: pes-innovation-lab/site-images
          path: images-repo
          token: ${{ secrets.REPO_PAT }}

      - name: Copy images to images repo
        run: |
          cd blog-repo
          blogs=$(find public/images/blogs -mindepth 1 -maxdepth 1 -type d -printf '%f\n')

          for blog in $blogs; do
            echo "Copying images for blog: $blog"
            mkdir -p ../images-repo/public/images/blogs/$blog
            cp -r public/images/blogs/$blog/* ../images-repo/public/images/blogs/$blog/ || true
          done

      - name: Commit & push images
        run: |
          cd images-repo
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Add blog images from PR #${{ github.event.pull_request.number }}" || echo "No new images"
          git push origin HEAD:main


      - name: Cleanup blog repo (remove images + rewrite links)
        run: |
          cd blog-repo
          BASE_URL="https://site-images.pages.dev/public/images/blogs"

          blogs=$(find ../images-repo/public/images/blogs -mindepth 1 -maxdepth 1 -type d -printf '%f\n' || true)

          if [ -z "$blogs" ]; then
            echo "No images uploaded, skipping cleanup & link rewrite."
            exit 0
          fi

          for blog in $blogs; do
            echo "Rewriting image links for blog: $blog"

            find blogs/$blog -name "*.md" | while read file; do
              sed -i "s|(/images/blogs/$blog/|($BASE_URL/$blog/|g" "$file"
            done

            git rm -rf public/images/blogs/$blog || true
          done

          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Remove images and rewrite Markdown links for PR #${{ github.event.pull_request.number }}" || echo "No cleanup changes"
          git push origin HEAD:main


